DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS ApplicationUser;

create table if not exists TASK (
id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key,
description varchar(7000000));

create table if not exists ApplicationUser (
id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key,
username varchar(64),
password varchar(64));
